sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache
    - $TRAVIS_BUILD_DIR/apache-solr-8.0.0
    - $TRAVIS_BUILD_DIR/apache-solr-8.0.0.tgz

php:
  - 7.4snapshot
  - 7.3
  - 7.2
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=5.1 WP_MULTISITE=1
  - WP_VERSION=5.1 WP_MULTISITE=0
  - WP_VERSION=5.0 WP_MULTISITE=1
  - WP_VERSION=5.0 WP_MULTISITE=0
  - WP_VERSION=4.9 WP_MULTISITE=1
  - WP_VERSION=4.9 WP_MULTISITE=0
  - WP_TRAVISCI=phpcs

matrix:
  exclude:
    - php: 7.4snapshot
      env: WP_VERSION=4.9 WP_MULTISITE=1
    - php: 7.4snapshot
      env: WP_VERSION=4.9 WP_MULTISITE=0
    - php: 7.3
      env: WP_VERSION=4.9 WP_MULTISITE=1
    - php: 7.3
      env: WP_VERSION=4.9 WP_MULTISITE=0
  fast_finish: true

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      composer global require "phpunit/phpunit=4.8.*|5.7.*"
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer global require wp-coding-standards/wpcs
      composer global require phpcompatibility/phpcompatibility-wp
      phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs,$HOME/.composer/vendor/phpcompatibility/phpcompatibility-wp
    fi
  - composer install
  - bash bin/install-solr.sh

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit --exclude-group multisite
      WP_MULTISITE=1 phpunit --exclude-group singlesite
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      phpcs -i
      phpcs
    fi
