sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache
    - $TRAVIS_BUILD_DIR/apache-solr-8.0.0
    - $TRAVIS_BUILD_DIR/apache-solr-8.0.0.tgz

php:
  - 7.3
  - 7.2
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=5.6 WP_MULTISITE=1
  - WP_VERSION=5.6 WP_MULTISITE=0
  - WP_VERSION=5.5 WP_MULTISITE=1
  - WP_VERSION=5.5 WP_MULTISITE=0
  - WP_VERSION=5.4 WP_MULTISITE=1
  - WP_VERSION=5.4 WP_MULTISITE=0

matrix:
  fast_finish: true

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      composer require phpunit/phpunit ^7.0.0
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer global require wp-coding-standards/wpcs
      phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs,$HOME/.composer/vendor/phpcompatibility/phpcompatibility-wp
    fi
  - vendor/bin/phpunit --version
  - composer install
  - vendor/bin/phpunit --version
  - bash bin/install-solr.sh

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      vendor/bin/phpunit --exclude-group multisite
      WP_MULTISITE=1 vendor/bin/phpunit --exclude-group singlesite
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      phpcs
    fi
